### ISSUE TITLE
Plans fulfillment order

### ISSUE THREAD

**Issue by xgasior** [MacakM/PV247-Expense-Manager#25]
Plans are checked by time, if there is enough money, plan maybe set as completed. But what would be the order to complete plans, if there are more than 1, but not all of them, that can be closed? 

Maybe this should do user himself, by clicking on plan, that can be set as compled.

We have to decide, how to do this.

**Comment by MacakM** [comment]
I think that user should do it himself because system cannot know which plan user fulfilled in real life.

**Comment by mayoturis** [comment]
If we don't want to complicate it we can do it just by the time when user created them. Let's if it is more important for him to save 10000kč on new laptop than 20000kč on some trip, he will first create the plan with laptop. But this brings the problem when the first plans needs more money than later (though it could be still solved).

> system cannot know which plan user fulfilled in real life

Maybe user first wants to see how much he saved (which plans he fulfilled) and only than he will fulfill it in real life :)

**Comment by MacakM** [comment]
But what if user fulfilled the plan to buy a PC and then in the shop he will find out that they don't have that PC and he have to wait for a month while they deliver it?
It is much more user friendly to let him click that he fulfilled the plan in real life imho...

**Comment by mayoturis** [comment]
okey, you are right
