### ISSUE TITLE
Distinction between periodic and non periodic costs in filtering

### ISSUE THREAD

**Issue by mayoturis** [MacakM/PV247-Expense-Manager#31]
I think there might be a small issue with ListCostInfosQuery and CostInfoModelFilter and the implementation of filtering by Periodicity. In my opinion current implementation (mainly following lines) doesn't allow filter non-permanent costs

if (Filter.Periodicity != null)
{
        costInfos = costInfos.Where(costInfo => costInfo.Periodicity == Filter.Periodicity.Value);
}

If the Periodicity is null no filtering will be applied but we need to somehow filter non-permanent costs. I would suggest adding new item to Periodicity enum (called let's say NONE) and not allow null values for Periodicity in CostInfoModel

**Comment by xgasior** [comment]
As i said before, we may add Periodicity.NONE to Periodicity enum, do you agree?

**Comment by xgasior** [comment]
Lets use Periodicity.None to get nonperiodic costs
