### ISSUE TITLE
Spacing in coding rules

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#43]
There are no rules on how many empty lines should be between class members, how to deal with empty lines within the method and so forth.

This leads to inconsistencies, e.g. there are plenty XML comments that are not separated from member above them, yet plenty of places where there is a free line. Some methods end with an empty line before closing brackets, some don't... Sort these out.

**Comment by xgasior** [comment]
I have updated readme and applied those rules over whole solution.
