### ISSUE TITLE
CostType seeding at database creation

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#62]
With fresh DB, there is no way to add new expense as there is no _CostType_. There is also no UI to add a new one.

**Comment by JaroslavDavidek** [comment]
CostTypes are now seeded via DB. CostType creations should be implemented within PL, so I am handing this over to mayoturis

**Comment by mayoturis** [comment]
actually, it was decided that CostTypes will be seeded at the database creation with some basic values (food, fun, accomodation, other, ...) which user can choose from

**Comment by mayoturis** [comment]
Will be solved in #70
