### ISSUE TITLE
Keep your master branch error-less

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#63]
This applies on the build as well as on run-time (it might happen here and there as code is still in development, but not right we default route is accessed). 

After login, there seems to be something wrong with Expenses:

````
An unhandled exception occurred while processing the request.

NullReferenceException: Object reference not set to an instance of an object.
MoveNext in Index.cshtml
    @if (Model.Expenses.Count == 0)
````

**Comment by mayoturis** [comment]
Fixed in a33d0dbcab7660ab77f6c016b445d0ec9eb7adb2
