### ISSUE TITLE
Still too many public classes

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#64]
Almost all classes are public in all your assemblies. To fix this, you need to do following: 
* test projects should have InternalVisibleTo attribute set to project they test (no other!)
* ``// Register all repositories`` and ``// Register all query objects`` should not be present in the _RegisterBusinessLayerDependencies_. These should actually not be (public) dependencies at all because they will alway be created with the same scope as the service itself. The service layer is supposed to separate you from these implementations.
   * Create an internal constructor for each service/facade that requires repository or query object (it will actually require only an interface, not a concrete type). 
   * Create a public constructor that will call the internal one, creating required instances of the type "on fly"
* make all your classes internal (a simple replace of "public class" with "internal class" should do the trick) and only make public those, that are absolutely necessary to be public - meaning models and interface(s) for operating with context in database layer; DTOs and services (or facades) in service layer; that is it.

**Comment by JaroslavDavidek** [comment]
Either separate DI within BusinessLayer or FactoryPattern should be used.
