### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#69]
Regions mean code smell. Especially in a project of this size. 

In the case of _ExpenseController_, it means the controller has way too many responsibilities that have to be split in multiple controllers.

In the case of _Helpers_ regions, these should be mitigated. Either move member to new files (especially classes ;)) or create some extension method (so new files again) or move the private methods freely within the file according to your coding rules.

In the case of _faced_, there are public methods without references (another code smell ;)) that should be removed. Also if facades are used in multiple places while only part of "facaded" classes is used in each, it means that faced is poorly designed and should be changed.

**Comment by JaroslavDavidek** [comment]
Relates to #41
