### ISSUE TITLE
Missing XML comments

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#7]
For all projects, go to project's properties and check "XML documentation file" for all configurations on Build tab. Rebuild solution and fix all the CS1591 warning.

Do not blindly add comments, always consider whether given member has to be public. Also, comments should add a value, not just repeat known information (e.g. UserName property with a description "User name" is pointless, while "Unique name of user used to distinguish between individual accounts" provides some extra information)

**Comment by MacakM** [comment]
When comment can't add some value, should I omit it or should I make it without value? Properties Name, Surname, Age, etc. is really hard to comment with some value.

**Comment by PetrSvirak** [comment]
Never omit comments in public API. Always image a person that got puzzled by your API's member names and tries to find their way.
For the name, it is suitable to say it is a given name of a person.
The surname is sometimes referred to as "last name" or, even better, "family name" – so if one is not really proficient in English, they can still understand the meaning of the property's value.
For the age (and all other numeric values), it is always useful to include measuring unit in the comment (e.g. "Number of years since the person's birth date").
Nobody said it will be easy, yet it is possible almost every time to bring an extra value.
