### ISSUE TITLE
Creating "new expense"

### ISSUE THREAD

**Issue by PetrSvirak** [MacakM/PV247-Expense-Manager#77]
It is possible to create an income or expense with 0 value - leads to +0 or -0 items in the list. This is bit weird.

Also, while "[income](https://en.oxforddictionaries.com/definition/income)" is totally valid term in this context. However, "[outcome](https://en.oxforddictionaries.com/definition/outcome)" is not its opposite. Moreover, menu item, list heading and dialog title is a bit misleading as "[expense](https://en.oxforddictionaries.com/definition/expense)" is actually one of the opposites of the "income".

One more think related to creating a new item, after first logic, I wanna try how it works. I click Add and see no category, thus cannot add anything. You put some time to add budget if I have none; do the same for the category.

**Comment by PetrSvirak** [comment]
Another thing: When I omit the description, I still do not know where is the problem as I'm only briefed by some generic error message. Moreover, if I add the description, the item is not stored at all while system says it is.

**Comment by PetrSvirak** [comment]
One cannot add expense for another day that the current one. This should be possible - some simple calendar widget with preset today's date?

**Comment by PetrSvirak** [comment]
I put some comments in the commit. Fix these. Also, replace all hard-coded labels in views with resource strings (I speak only about views affected in this task).

**Comment by mayoturis** [comment]
Since I haven't received any feedback, I am not sure whether commits generate notifications. Comments should, so I am writing one :)

**Comment by PetrSvirak** [comment]
I guess the issue would have to be open in order for GitHub to send notifications on commits.
Anyway, I still lack a bit more attention to details; for example, resource strings can be read by attribute or at least dynamically using a [resource manager](http://stackoverflow.com/a/1573376/1138663) and should be applied (at least) on both enums in the above-mentioned commit. Also, helper methods were used where tag-helpers were suggested. But, hell, it is x-mass, so let's close the issue finally a completely.
